# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag to be created along with release'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      Commit: 
        description: 'Commit reference to create tag from'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  createRelease:
      runs-on: ubuntu-latest
      name: Create Release
      steps:
        - uses: aurelien-baudet/workflow-dispatch@v2.1.1
          with:
           repo: jjkiely/testRelease
           token: ${{ secrets.ACCESS_TOKEN }}
           workflow: manual.yml
           inputs: '{ "Tag": "${{ inputs.Tag }}", "Commit": "${{ inputs.Commit }}"}'
           wait-for-completion: true
           display-workflow-run-url: true
